
<html>
    <head>
        <title>Oferta współpracy Comes Consulting Group</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            a { color: #000; }
            body { font-family: Helvetica; color: #000033; }
            div.body  {background: url(http://comescon.pl/mail/BACKMAIL.png); background-size: cover; background-position: center;}
            div {text-align: center; position: relative; }
            div.main { width: 700px; border: 0; margin: auto; padding: 15px;  }
            div.head { text-align: justify; }
            div.head img { margin-left: 1px; position: relative; float: left; }
            div.head div.adres {margin-top: 15px; text-align: right; float: right; }
            h4 { font-family: helvetica; }
            p  { text-align: justify; font-family: arial; text-indent: 10%;   }
            div.content { background:  #fff; padding: 25px; text-align: left;  }
            div.footer { color: #fff; text-shadow: 1px 1px 1px #000;  }
            div.footer table { color: #fff;}
            ul { list-style-type: circle; }
            li {  }
        </style>
    </head>
    <body>
        <div class="body">
            <center>
                <div class="main">

                    <div class="head">
                        <img src="http://comescon.pl/images/logo.png" height="70">
                        <div class="adres" style="text-align: left">
                            Wycena Przedsiębiorstw, spółek, akcji
                            <br><a href="http://www.comescon.pl">www.comescon.pl</a> /  <a href="mailto:biuro@comescon.pl">biuro@comescon.pl</a>
                        </div>
                        <br style="clear: both">
                    </div>
                    <div class="content">
                        <p style="text-align: right">
                            <b> <?php echo $csv[0]; ?></b><br>
                            <?php echo ucfirst($csv[1]); ?>
                        </p>
                        <br>
                        <h3>Szanowni Państwo,</h3>
                        <br>
                        <p>Głównym zadaniem firmy Comes Consulting Group jest <b>wycena przedsiębiorstw, nieruchomości, ruchomości, i innych rzeczy</b> w zależności od potrzeb Zleceniodawcy. Wyceny są dokonywane dla potrzeb osób fizycznych, prawnych. Szacujemy wszystkie rodzaje nieruchomości,  przedsiębiorstw, środków trwałych od 2003r. </p>
                        <p>Możemy się wykazać wieloletnią praktyką, doskonałymi umiejętnościami, różnorakim i bogatym doświadczeniem w wycenie każdego segmentu nieruchomości. Przygotowywane przez nas operaty szacunkowe, raporty, analizy wykonywane są dla potrzeb: inwestycyjnych, rachunkowości przedsiębiorstwa, egzekucyjnych, sądowych, sprzedaży, przekształceń własnościowych i wielu innych.</p>
                        <p>Współpracujemy z wieloma firmami działającymi na rynku nieruchomości, a także z kancelariami prawnymi posiadającymi duże doświadczenie w obsłudze prawnej firm.</p>
                        <p>Nasza działalność charakteryzuje się przede wszystkim: rzetelnością, systematycznością, wysoką jakością usług, kompetentną oraz wyspecjalizowaną kadrą. Naszym atutem jest ponadto szybkość realizacji otrzymanych zleceń.</p>

                        <p>
                            <b>Oferta obejmuje wycenę spółek, przedsiębiorstw, akcji, udziałów oraz dóbr niematerialnych (marka, patent, know-how, znak towarowy, relacje klienckie, opcje menedżerskie, kapitał intelektualny itp.).
                                W zależności od charakteru prowadzonego biznesu, wielkości aktywów oraz oczekiwań klienta dobieramy optymalny zestaw różnych metod wyceny dający przedsiębiorcy pełen obraz wartości spółki oraz czynników kreujących wartość.
                            </b>
                        </p>

                        <table>
                            <tr>
                                <td>
                                    <b>Wykonujemy również usługi w zakresie wyceny: </b><br>
                                    <ul>
                                        <li>	obiektów budowlanych, m.in. budynków i budowli,</li> 
                                        <li>	lokali mieszkalnych, użytkowych, produkcyjnych, </li>
                                        <li>	gruntów rolnych, budowlanych
                                            i rekreacyjnych, 
                                        <li>	gruntów zadrzewionych </li>
                                        <li>i zakrzewionych, </li>
                                        <li>	lasów, upraw sadowniczych 
                                            i pojedynczych drzew, </li>
                                        <li>	zbiorników wodnych sztucznych 
                                            i naturalnych </li>
                                        <li>	maszyn i urządzeń, linii technologicznych, pojazdów, </li>
                                        <li>	firm, przedsiębiorstw i zakładów produkcyjnych </li>
                                        <li>	oraz innych nie wymienionych.</li>
                                    </ul>
                                </td>
                                <td>
                                    <div style="margin-top: 30px; text-align: left;">
                                        <b>Dla potrzeb:</b>
                                        <ul>
                                            <ul>
                                                <li>	postępowania administracyjnego, </li>
                                                <li>	postępowania przetargowego, sprzedaży nieruchomości,</li>
                                                <li>	postępowania komorniczego 
                                                    i sądowego, </li>
                                                <li>	sektora bankowego, publicznego, </li>
                                                <li>	przedsięwzięć developerskich, </li>
                                                <li>	obrotu wolnorynkowego, dzierżawy, najmu.</li>

                                            </ul>
                                    </div>
                                </td>
                            </tr>

                        </table>

                        <h3>
                            Zapraszamy do korzystania z naszych usług
                        </h3>
                        W imieniu Zespołu  <br><b>COMES CONSULTING GROUP</b>
                        <h4><b>Mirosław Zych</b>; rzeczoznawca majątkowy,<br>specjalista z zakresu wyceny przedsiębiorstw</h4>
                        <p>
                            <br>
                            <i>Powyższa oferta ma charakter informacyjny i nie stanowi oferty handlowej w rozumieniu art.66 §1 k.c. oraz innych właściwych przepisów prawnych. </i>
                        </p>

                    </div>
                    <div class="footer">
                        <table style="width: 100%;">
                            <tr>
                                <td style="width: 40%;">
                                    <h3>Comes Consulting Group</h3>
                                    tel. kom.: +48 604 722 080 <br>
                                    sekretariat :  +48 512 755 153

                                </td>

                                <td  style="width: 30%">
                                    Oddział Bytom:<br>
                                    ul. Drzymały 2/4<br>
                                    41-902 Bytom<br>
                                    tel.: +48 (32)281-79-14 

                                </td>
                                <td style="width: 30%">
                                    Oddział Kraków: <br>
                                    Aleja Pokoju 3/2 <br>
                                    31-548 Kraków <br>
                                    tel.: +48 (12)631-97-35

                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </center>
        </div>
    </body>
</html>

